create table uc4_job_definition (
    id number generated by default as identity primary key,
    uc4_object_id varchar2(128) not null,
    job_name varchar2(255) not null,
    object_type varchar2(32) not null,
    plan_name varchar2(255),
    folder_path varchar2(1024),
    team_code varchar2(64) not null,
    active number(1) default 1 not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint ck_uc4_job_definition_active check (active in (0, 1))
);

create index ix_uc4_job_definition_object
    on uc4_job_definition (uc4_object_id);

create index ix_uc4_job_definition_name
    on uc4_job_definition (job_name);

create index ix_uc4_job_definition_plan
    on uc4_job_definition (plan_name);

create table uc4_job_run_history (
    id number generated by default as identity primary key,
    uc4_run_id varchar2(128) not null,
    job_name varchar2(255) not null,
    plan_name varchar2(255),
    start_time timestamp not null,
    end_time timestamp,
    duration_seconds number(19),
    status varchar2(64),
    return_code number(10),
    last_report clob,
    business_date date not null,
    inserted_at timestamp not null default current_timestamp
);

create unique index ux_uc4_job_run_history_run
    on uc4_job_run_history (uc4_run_id);

create index ix_uc4_job_run_history_business_date
    on uc4_job_run_history (business_date);

create index ix_uc4_job_run_history_name_date
    on uc4_job_run_history (job_name, business_date);

create table uc4_job_anomaly_log (
    id number generated by default as identity primary key,
    job_name varchar2(255) not null,
    plan_name varchar2(255),
    run_id varchar2(128),
    business_date date not null,
    anomaly_type varchar2(64) not null,
    actual_duration_seconds number(19),
    avg_duration_seconds numeric(18, 2),
    min_duration_seconds number(19),
    max_duration_seconds number(19),
    deviation_percent numeric(8, 2),
    description clob not null,
    created_at timestamp not null default current_timestamp
);

create index ix_uc4_job_anomaly_log_business_date
    on uc4_job_anomaly_log (business_date);

create table uc4_report_subscription (
    id number generated by default as identity primary key,
    scope_type varchar2(16) not null check (scope_type in ('JOB', 'PLAN')),
    scope_value varchar2(255) not null,
    active number(1) default 1 not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint ck_uc4_report_subscription_active check (active in (0, 1))
);

create unique index ux_uc4_report_subscription_scope
    on uc4_report_subscription (scope_type, scope_value);
